apiVersion: v1
kind: Service
metadata:
  name: db-client-load-balancer
  namespace: db-client
spec:
  selector:
    app: db-client
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer