apiVersion: v1
kind: Pod
metadata:
  namespace: db-client
  name: db-client
  labels:
    app: db-client
spec:
  containers:
  - name: db-client
    image: rudzmic1/cloudhours-workshops:0.1
    ports:
    - containerPort: 5000