apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-app-daemon-set
  labels:
    app: MyApp
spec:
  selector:
    matchLabels:
      app: MyApp
  template:
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
      - name: MyApp
        image: rudzmic1/cloudhours-workshops:0.1
        