apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-app-daemon-set
  labels:
    app: my-app-daemon-set
spec:
  selector:
    matchLabels:
      app: my-app-daemon-set
  template:
    metadata:
      labels:
        app: my-app-daemon-set
    spec:
      containers:
      - name: my-app
        image: rudzmic1/cloudhours-workshops:0.1
        