apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-restaurant
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /pizza
        backend:
          serviceName: my-pizza-service-cluster-ip
          servicePort: 5000